# syntax=docker/dockerfile:1.7

FROM eclipse-temurin:17-jre AS runner
WORKDIR /app
COPY build/libs/payment-processing-system-0.0.1-SNAPSHOT.jar app.jar
ENV SPRING_MAIN_WEB_APPLICATION_TYPE=NONE \
    SPRING_PROFILES_ACTIVE=docker \
    SPRING_MAIN_APPLICATION_CLASS=com.example.payments.worker.WorkerApplication
ENTRYPOINT ["java","-jar","/app/app.jar"]

