spring:
  application:
    name: payment-processing-system
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: payments
    password: payments
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:payments}
    password: ${SPRING_RABBITMQ_PASSWORD:payments}
    virtual-host: ${SPRING_RABBITMQ_VHOST:/}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, trace
  endpoint:
    health:
      probes:
        enabled: true

  tracing:
    exporter:
      zipkin:
        enabled: true
        endpoint: ${MANAGEMENT_TRACING_EXPORTER_ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
    sampling:
      probability: 0.1
  metrics:
    tags:
      application: ${spring.application.name}

subscription:
  retry:
    auto-cancel-days: 30
    schedule-cron: "0 */5 * * * *"

security:
  jwt:
    secret: "ZHNsa2YzNzlLOHJ1ZzQySWFiNkZsU2UzTnhpU0J6VTRqZkpnd0t4VzFRTlJ3Ukh5aXAzTHN4RDJneHhQSlR1MDk3bUYyV3lyQTM4UWRhUw=="
    expiration-seconds: 3600
    issuer: "payments-system"
    audience: "payments-clients"

authorize-net:
  api-login-id: "${AUTHORIZE_NET_LOGIN_ID:4k4u4QpccWNx}"
  transaction-key: "${AUTHORIZE_NET_TRANSACTION_KEY:7Er957Hr87L29Yyr}"
  endpoint: "https://apitest.authorize.net/xml/v1/request.api"
  webhook-signature-key: "${AUTHORIZE_NET_SIGNATURE_KEY:1F72E7B605E7512D046BBDDD8A284100108DE259919648E2B70B08ABFDE54281EECE2280B244D28C4F61D2CDDD6BA5C3AD4748D100AFF4388726B8A4AE153F3C}"
  default-currency: "${AUTHORIZE_NET_DEFAULT_CURRENCY:USD}"
